# Generated by Django 2.2 on 2020-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Powerball',
            fields=[
                ('draw_number', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('draw_type', models.CharField(default='6/50', max_length=64)),
                ('draw_date', models.DateTimeField()),
                ('ball1', models.IntegerField(default=1)),
                ('ball2', models.IntegerField(default=1)),
                ('ball3', models.IntegerField(default=1)),
                ('ball4', models.IntegerField(default=1)),
                ('ball5', models.IntegerField(default=1)),
                ('result', models.TextField()),
                ('power_ball', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Powerball Draw',
                'verbose_name_plural': 'Powerball Draws',
            },
        ),
    ]
